export const PERMISSION_CONSTANTS = {
  // module.action — lowercase, snake_case action, dot separator.
  CODE_REGEX: /^[a-z][a-z0-9_]{1,49}\.[a-z][a-z0-9_]{1,49}$/,

  MODULE: "users",

  ACTIONS: {
    VIEW: "view",
    CREATE: "create",
    UPDATE: "update",
    DELETE: "delete",
    RESTORE: "restore",
    CHANGE_STATUS: "change_status",
    BULK_ACTION: "bulk_action",
    RESET_PASSWORD: "reset_password",
    MANAGE_2FA: "manage_2fa",
    FORCE_LOGOUT: "force_logout",
  },
} as const;

/**
 * Fully-qualified permission codes for this module, ready to use in
 * @RequirePermissions(...) decorators.
 */
export const USERS_PERMISSIONS = {
  VIEW: `${PERMISSION_CONSTANTS.MODULE}.${PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  CREATE: `${PERMISSION_CONSTANTS.MODULE}.${PERMISSION_CONSTANTS.ACTIONS.CREATE}`,
  UPDATE: `${PERMISSION_CONSTANTS.MODULE}.${PERMISSION_CONSTANTS.ACTIONS.UPDATE}`,
  DELETE: `${PERMISSION_CONSTANTS.MODULE}.${PERMISSION_CONSTANTS.ACTIONS.DELETE}`,
  RESTORE: `${PERMISSION_CONSTANTS.MODULE}.${PERMISSION_CONSTANTS.ACTIONS.RESTORE}`,
  CHANGE_STATUS: `${PERMISSION_CONSTANTS.MODULE}.${PERMISSION_CONSTANTS.ACTIONS.CHANGE_STATUS}`,
  BULK_ACTION: `${PERMISSION_CONSTANTS.MODULE}.${PERMISSION_CONSTANTS.ACTIONS.BULK_ACTION}`,
  RESET_PASSWORD: `${PERMISSION_CONSTANTS.MODULE}.${PERMISSION_CONSTANTS.ACTIONS.RESET_PASSWORD}`,
  MANAGE_2FA: `${PERMISSION_CONSTANTS.MODULE}.${PERMISSION_CONSTANTS.ACTIONS.MANAGE_2FA}`,
  FORCE_LOGOUT: `${PERMISSION_CONSTANTS.MODULE}.${PERMISSION_CONSTANTS.ACTIONS.FORCE_LOGOUT}`,
} as const;
