export const JOBS_PERMISSION_CONSTANTS = {
  MODULE: 'jobs',
  ACTIONS: {
    VIEW: 'view',
    CREATE: 'create',
    UPDATE: 'update',
    DELETE: 'delete',
    CLOSE: 'close',
    VIEW_GP: 'view_gp',
  },
} as const;

export const JOBS_PERMISSIONS = {
  VIEW: `${JOBS_PERMISSION_CONSTANTS.MODULE}.${JOBS_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  CREATE: `${JOBS_PERMISSION_CONSTANTS.MODULE}.${JOBS_PERMISSION_CONSTANTS.ACTIONS.CREATE}`,
  UPDATE: `${JOBS_PERMISSION_CONSTANTS.MODULE}.${JOBS_PERMISSION_CONSTANTS.ACTIONS.UPDATE}`,
  DELETE: `${JOBS_PERMISSION_CONSTANTS.MODULE}.${JOBS_PERMISSION_CONSTANTS.ACTIONS.DELETE}`,
  CLOSE: `${JOBS_PERMISSION_CONSTANTS.MODULE}.${JOBS_PERMISSION_CONSTANTS.ACTIONS.CLOSE}`,
  VIEW_GP: `${JOBS_PERMISSION_CONSTANTS.MODULE}.${JOBS_PERMISSION_CONSTANTS.ACTIONS.VIEW_GP}`,
} as const;
