/**
 * Auto-seeded onto every SEA_FCL_IMPORT job at creation (Ch.11.2 — 14 checkpoints).
 */
export const SEA_FCL_IMPORT_MILESTONES: string[] = [
  "BOOKING_CREATED",
  "MBL_RECEIVED",
  "ARRIVAL_VESSEL_CONFIRMED",
  "CARGO_ARRIVED_AT_POD",
  "CAN_SENT",
  "CUSTOMS_ENTRY_FILED",
  "CUSTOMS_CLEARED",
  "DO_ISSUED",
  "CONTAINER_PICKED_UP",
  "CONTAINER_DELIVERED_TO_CONSIGNEE",
  "CONTAINER_RETURNED_TO_SHIPPING_LINE",
  "INVOICE_RAISED",
  "PAYMENT_RECEIVED",
  "JOB_CLOSED",
];
