import { ReportParamDef } from "../types/report.types";
import { ReportTemplateSeed } from "./ops-list-phase1.seed";

const invoiceIdParam: ReportParamDef = {
  name: "invoice_id",
  label: "Invoice",
  type: "uuid",
  required: true,
  default: null,
};

const jobIdParam: ReportParamDef = {
  name: "job_id",
  label: "Job",
  type: "uuid",
  required: true,
  default: null,
};

const quotationIdParam: ReportParamDef = {
  name: "quotation_id",
  label: "Quotation",
  type: "uuid",
  required: true,
  default: null,
};

const partyIdParam: ReportParamDef = {
  name: "party_id",
  label: "Party",
  type: "uuid",
  required: false,
  default: null,
};

const dateFrom = {
  name: "date_from",
  label: "From date",
  type: "date" as const,
  required: false,
  default: null,
};

const dateTo = {
  name: "date_to",
  label: "To date",
  type: "date" as const,
  required: false,
  default: null,
};

/** Priority document / catalog packs (additive; inactive until activate). */
export const PRIORITY_PACKS_SEED: ReportTemplateSeed[] = [
  {
    code: "INVOICE_REPORT_FORMAT_1_TAX_INVOICE_INDIA",
    name: "Invoice Report Format 1 — Tax Invoice India",
    family: "commercial",
    contexts: ["invoice"],
    formats: ["PDF"],
    description: "FRESA Format-1 tax invoice (catalog pack). Does not replace POST /invoices/:id/pdf.",
    is_active: false,
    renderer_key: "commercial.invoice_tax_india_1",
    sort_order: 1000,
    parameters_schema: [invoiceIdParam],
  },
  {
    code: "INVOICE_REPORT_FORMAT_2_TAX_INVOICE_INDIA",
    name: "Invoice Report Format 2 — Tax Invoice India",
    family: "commercial",
    contexts: ["invoice"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "commercial.invoice_tax_india_2",
    sort_order: 1001,
    parameters_schema: [invoiceIdParam],
  },
  {
    code: "INVOICE_REPORT_FORMAT_SUMMARY_INDIA",
    name: "Invoice Report — Summary India",
    family: "commercial",
    contexts: ["invoice"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "commercial.invoice_summary_india",
    sort_order: 1002,
    parameters_schema: [invoiceIdParam],
  },
  {
    code: "INVOICE_REPORT_FORMAT_10_STANDARD_INVOICE",
    name: "Invoice Report Format 10 — Standard Invoice",
    family: "commercial",
    contexts: ["invoice"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "commercial.invoice_standard",
    sort_order: 1003,
    parameters_schema: [invoiceIdParam],
  },
  {
    code: "INVOICE_REPORT_FORMAT_6_SIMPLE_INVOICE_INDIA",
    name: "Invoice Report Format 6 — Simple Invoice India",
    family: "commercial",
    contexts: ["invoice"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "commercial.invoice_simple_india",
    sort_order: 1004,
    parameters_schema: [invoiceIdParam],
  },
  {
    code: "INVOICE_REPORT_FORMAT_8_STANDARD_INVOICE_ARABIC",
    name: "Invoice Report Format 8 — Standard Invoice Arabic",
    family: "commercial",
    contexts: ["invoice"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "commercial.invoice_arabic",
    sort_order: 1005,
    parameters_schema: [invoiceIdParam],
  },
  {
    code: "INVOICE_REPORT_FORMAT_9_STANDARD_INVOICE_USA",
    name: "Invoice Report Format 9 — Standard Invoice USA",
    family: "commercial",
    contexts: ["invoice"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "commercial.invoice_usa",
    sort_order: 1006,
    parameters_schema: [invoiceIdParam],
  },
  {
    code: "INVOICE_REPORT_FORMAT_21_WAREHOUSE_INVOICE",
    name: "Invoice Report Format 21 — Warehouse Invoice",
    family: "commercial",
    contexts: ["invoice"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "commercial.invoice_warehouse",
    sort_order: 1007,
    parameters_schema: [invoiceIdParam],
  },
  {
    code: "OPS_LIST_GENERIC",
    name: "Operations List (generic)",
    family: "ops_list",
    contexts: ["list"],
    formats: ["PDF", "XLSX", "CSV"],
    is_active: false,
    renderer_key: "ops.list_generic",
    sort_order: 50,
    parameters_schema: [dateFrom, dateTo],
  },
  {
    code: "SEA_HBL_DRAFT",
    name: "HBL Draft (document)",
    family: "sea_docs",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "sea.hbl_draft",
    sort_order: 2000,
    parameters_schema: [jobIdParam],
  },
  {
    code: "SEA_HBL_ORIGINAL",
    name: "HBL Original (document)",
    family: "sea_docs",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "sea.hbl_original",
    sort_order: 2001,
    parameters_schema: [jobIdParam],
  },
  {
    code: "SEA_ARRIVAL_NOTICE",
    name: "Arrival Notice (document)",
    family: "sea_docs",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "sea.arrival_notice",
    sort_order: 2002,
    parameters_schema: [jobIdParam],
  },
  {
    code: "SEA_DELIVERY_ORDER",
    name: "Delivery Order (document)",
    family: "sea_docs",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "sea.delivery_order",
    sort_order: 2003,
    parameters_schema: [jobIdParam],
  },
  {
    code: "SEA_CARGO_MANIFEST",
    name: "Cargo Manifest (document)",
    family: "sea_docs",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "sea.cargo_manifest",
    sort_order: 2004,
    parameters_schema: [jobIdParam],
  },
  {
    code: "SEA_STUFFING_REPORT",
    name: "Stuffing Report (document)",
    family: "sea_docs",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "sea.stuffing_report",
    sort_order: 2005,
    parameters_schema: [jobIdParam],
  },
  {
    code: "AIR_HAWB_DRAFT",
    name: "HAWB Draft",
    family: "air_docs",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "air.hawb_draft",
    sort_order: 3000,
    parameters_schema: [jobIdParam],
  },
  {
    code: "AIR_HAWB_FINAL",
    name: "HAWB Final",
    family: "air_docs",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "air.hawb_final",
    sort_order: 3001,
    parameters_schema: [jobIdParam],
  },
  {
    code: "AIR_MAWB",
    name: "MAWB",
    family: "air_docs",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "air.mawb",
    sort_order: 3002,
    parameters_schema: [jobIdParam],
  },
  {
    code: "AIR_ARRIVAL_NOTICE",
    name: "Air Arrival Notice",
    family: "air_docs",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "air.arrival_notice",
    sort_order: 3003,
    parameters_schema: [jobIdParam],
  },
  {
    code: "AIR_DELIVERY_ORDER",
    name: "Air Delivery Order",
    family: "air_docs",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "air.delivery_order",
    sort_order: 3004,
    parameters_schema: [jobIdParam],
  },
  {
    code: "QUOTATION_STANDARD",
    name: "Quotation Standard (catalog)",
    family: "quotation",
    contexts: ["quotation"],
    formats: ["PDF"],
    description: "Catalog quotation format — does not replace POST /quotations/:id/pdf.",
    is_active: false,
    renderer_key: "quotation.standard",
    sort_order: 4000,
    parameters_schema: [quotationIdParam],
  },
  {
    code: "FINANCE_AGING",
    name: "Receivables Aging",
    family: "finance",
    contexts: ["list", "party"],
    formats: ["PDF", "XLSX", "CSV"],
    is_active: false,
    renderer_key: "finance.aging",
    sort_order: 5000,
    parameters_schema: [partyIdParam],
  },
  {
    code: "FINANCE_SOA",
    name: "Statement of Account",
    family: "finance",
    contexts: ["party", "list"],
    formats: ["PDF", "XLSX", "CSV"],
    is_active: false,
    renderer_key: "finance.soa",
    sort_order: 5001,
    parameters_schema: [
      { ...partyIdParam, required: true },
    ],
  },
  {
    code: "FINANCE_TRIAL_BALANCE",
    name: "Trial Balance (catalog)",
    family: "finance",
    contexts: ["gl"],
    formats: ["PDF", "XLSX", "CSV"],
    is_active: false,
    renderer_key: "finance.trial_balance",
    sort_order: 5002,
    parameters_schema: [],
  },
  {
    code: "FINANCE_VOUCHER",
    name: "Voucher Print",
    family: "finance",
    contexts: ["gl"],
    formats: ["PDF", "XLSX"],
    is_active: false,
    renderer_key: "finance.voucher",
    sort_order: 5003,
    parameters_schema: [
      {
        name: "voucher_id",
        label: "Voucher",
        type: "uuid",
        required: true,
        default: null,
      },
    ],
  },
  {
    code: "FINANCE_JOURNAL_VOUCHER",
    name: "Journal Voucher",
    family: "finance",
    contexts: ["gl"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "finance.journal_voucher",
    sort_order: 5005,
    parameters_schema: [
      {
        name: "voucher_id",
        label: "Voucher",
        type: "uuid",
        required: true,
        default: null,
      },
    ],
  },
  {
    code: "FINANCE_PAYMENT_VOUCHER",
    name: "Payment Voucher",
    family: "finance",
    contexts: ["gl"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "finance.payment_voucher",
    sort_order: 5006,
    parameters_schema: [
      {
        name: "voucher_id",
        label: "Voucher",
        type: "uuid",
        required: true,
        default: null,
      },
    ],
  },
  {
    code: "FINANCE_RECEIPT_VOUCHER",
    name: "Receipt Voucher",
    family: "finance",
    contexts: ["gl"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "finance.receipt_voucher",
    sort_order: 5007,
    parameters_schema: [
      {
        name: "voucher_id",
        label: "Voucher",
        type: "uuid",
        required: true,
        default: null,
      },
    ],
  },
  {
    code: "FINANCE_OUTSTANDING_LETTER",
    name: "Outstanding Letter",
    family: "finance",
    contexts: ["party"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "finance.outstanding_letter",
    sort_order: 5004,
    parameters_schema: [{ ...partyIdParam, required: true }],
  },
  {
    code: "WMS_ASN",
    name: "Advance Shipping Note",
    family: "wms",
    contexts: ["wms", "list"],
    formats: ["PDF", "XLSX", "CSV"],
    is_active: false,
    renderer_key: "wms.asn",
    sort_order: 6000,
    parameters_schema: [
      {
        name: "asn_id",
        label: "ASN",
        type: "uuid",
        required: false,
        default: null,
      },
    ],
  },
  {
    code: "WMS_GRN",
    name: "Goods Receipt Note",
    family: "wms",
    contexts: ["wms", "list"],
    formats: ["PDF", "XLSX"],
    is_active: false,
    renderer_key: "wms.grn",
    sort_order: 6002,
    parameters_schema: [
      {
        name: "grn_id",
        label: "GRN",
        type: "uuid",
        required: false,
        default: null,
      },
    ],
  },
  {
    code: "WMS_GDO",
    name: "Goods Delivery Order",
    family: "wms",
    contexts: ["wms", "list"],
    formats: ["PDF", "XLSX"],
    is_active: false,
    renderer_key: "wms.gdo",
    sort_order: 6003,
    parameters_schema: [
      {
        name: "gdo_id",
        label: "GDO",
        type: "uuid",
        required: false,
        default: null,
      },
    ],
  },
  {
    code: "WMS_WAREHOUSE_NOTE",
    name: "Warehouse Note",
    family: "wms",
    contexts: ["wms"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "wms.warehouse_note",
    sort_order: 6001,
    parameters_schema: [],
  },
  {
    code: "OTHER_BOOKING_CONFIRMATION",
    name: "Booking Confirmation",
    family: "other",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "other.booking_confirmation",
    sort_order: 7000,
    parameters_schema: [jobIdParam],
  },
  {
    code: "OTHER_PRE_ALERT",
    name: "Pre-Alert",
    family: "other",
    contexts: ["job"],
    formats: ["PDF"],
    is_active: false,
    renderer_key: "other.pre_alert",
    sort_order: 7001,
    parameters_schema: [jobIdParam],
  },
];
