export const MASTERS_PERMISSION_CONSTANTS = {
  MODULE: "masters",
  ACTIONS: {
    VIEW: "view",
    CREATE: "create",
    UPDATE: "update",
    DELETE: "delete",
  },
} as const;

export const MASTERS_PERMISSIONS = {
  VIEW: `${MASTERS_PERMISSION_CONSTANTS.MODULE}.${MASTERS_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  CREATE: `${MASTERS_PERMISSION_CONSTANTS.MODULE}.${MASTERS_PERMISSION_CONSTANTS.ACTIONS.CREATE}`,
  UPDATE: `${MASTERS_PERMISSION_CONSTANTS.MODULE}.${MASTERS_PERMISSION_CONSTANTS.ACTIONS.UPDATE}`,
  DELETE: `${MASTERS_PERMISSION_CONSTANTS.MODULE}.${MASTERS_PERMISSION_CONSTANTS.ACTIONS.DELETE}`,
} as const;
