-- Week 1–6 gap completion: docs enums, provisional charges, sub-jobs, scheduled pre-alert, status emails.

ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'E_AWB';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'BARCODE_LABEL';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'CONSIGNEE_LABEL';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'JOB_COSTING';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'FREIGHT_CERTIFICATE';

ALTER TYPE "EmailEventType" ADD VALUE IF NOT EXISTS 'MILESTONE_STATUS';
ALTER TYPE "EmailEventType" ADD VALUE IF NOT EXISTS 'USER_INVITE';
ALTER TYPE "EmailEventType" ADD VALUE IF NOT EXISTS 'WHATSAPP_OUTBOUND';

ALTER TABLE "job_charges"
  ADD COLUMN IF NOT EXISTS "is_provisional" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "jobs"
  ADD COLUMN IF NOT EXISTS "is_sub_job" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "pre_alert_scheduled_at" TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "pre_alert_to_email" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "pre_alert_message" TEXT,
  ADD COLUMN IF NOT EXISTS "pre_alert_sent_at" TIMESTAMPTZ;
