export const DOCUMENTATION_PERMISSION_CONSTANTS = {
  MODULE: "documentation",
  ACTIONS: {
    READ: "read",
    MANAGE: "manage",
    EDI_READ: "edi.read",
    EDI_SUBMIT: "edi.submit",
    UPLOAD: "upload",
    MPCI: "mpci",
  },
} as const;

export const DOCUMENTATION_PERMISSIONS = {
  READ: `${DOCUMENTATION_PERMISSION_CONSTANTS.MODULE}.${DOCUMENTATION_PERMISSION_CONSTANTS.ACTIONS.READ}`,
  MANAGE: `${DOCUMENTATION_PERMISSION_CONSTANTS.MODULE}.${DOCUMENTATION_PERMISSION_CONSTANTS.ACTIONS.MANAGE}`,
  EDI_READ: `${DOCUMENTATION_PERMISSION_CONSTANTS.MODULE}.${DOCUMENTATION_PERMISSION_CONSTANTS.ACTIONS.EDI_READ}`,
  EDI_SUBMIT: `${DOCUMENTATION_PERMISSION_CONSTANTS.MODULE}.${DOCUMENTATION_PERMISSION_CONSTANTS.ACTIONS.EDI_SUBMIT}`,
  UPLOAD: `${DOCUMENTATION_PERMISSION_CONSTANTS.MODULE}.${DOCUMENTATION_PERMISSION_CONSTANTS.ACTIONS.UPLOAD}`,
  MPCI: `${DOCUMENTATION_PERMISSION_CONSTANTS.MODULE}.${DOCUMENTATION_PERMISSION_CONSTANTS.ACTIONS.MPCI}`,
} as const;
