export const SHIPMENTS_PERMISSION_CONSTANTS = {
  MODULE: "shipments",
  ACTIONS: {
    VIEW: "view",
    CREATE: "create",
    UPDATE: "update",
    DELETE: "delete",
    GENERATE: "generate",
  },
} as const;

export const SHIPMENTS_PERMISSIONS = {
  VIEW: `${SHIPMENTS_PERMISSION_CONSTANTS.MODULE}.${SHIPMENTS_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  CREATE: `${SHIPMENTS_PERMISSION_CONSTANTS.MODULE}.${SHIPMENTS_PERMISSION_CONSTANTS.ACTIONS.CREATE}`,
  UPDATE: `${SHIPMENTS_PERMISSION_CONSTANTS.MODULE}.${SHIPMENTS_PERMISSION_CONSTANTS.ACTIONS.UPDATE}`,
  DELETE: `${SHIPMENTS_PERMISSION_CONSTANTS.MODULE}.${SHIPMENTS_PERMISSION_CONSTANTS.ACTIONS.DELETE}`,
  GENERATE: `${SHIPMENTS_PERMISSION_CONSTANTS.MODULE}.${SHIPMENTS_PERMISSION_CONSTANTS.ACTIONS.GENERATE}`,
} as const;
