export const TRANSPORT_PERMISSION_CONSTANTS = {
  MODULE: 'transport',
  ACTIONS: {
    VIEW: 'view',
    MANAGE: 'manage',
  },
} as const;

export const TRANSPORT_PERMISSIONS = {
  VIEW: `${TRANSPORT_PERMISSION_CONSTANTS.MODULE}.${TRANSPORT_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  MANAGE: `${TRANSPORT_PERMISSION_CONSTANTS.MODULE}.${TRANSPORT_PERMISSION_CONSTANTS.ACTIONS.MANAGE}`,
} as const;
