export const WMS_PERMISSION_CONSTANTS = {
  MODULE: 'wms',
  ACTIONS: {
    VIEW: 'view',
    MANAGE_ITEMS: 'manage_items',
    MANAGE_ASN: 'manage_asn',
    MANAGE_GRN: 'manage_grn',
    MANAGE_GDO: 'manage_gdo',
    MANAGE_STOCK: 'manage_stock',
    MANAGE_TRANSFERS: 'manage_transfers',
    MANAGE_STORAGE: 'manage_storage',
    MANAGE_SETTINGS: 'manage_settings',
    VIEW_REPORTS: 'view_reports',
  },
} as const;

export const WMS_PERMISSIONS = {
  VIEW: `${WMS_PERMISSION_CONSTANTS.MODULE}.${WMS_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  MANAGE_ITEMS: `${WMS_PERMISSION_CONSTANTS.MODULE}.${WMS_PERMISSION_CONSTANTS.ACTIONS.MANAGE_ITEMS}`,
  MANAGE_ASN: `${WMS_PERMISSION_CONSTANTS.MODULE}.${WMS_PERMISSION_CONSTANTS.ACTIONS.MANAGE_ASN}`,
  MANAGE_GRN: `${WMS_PERMISSION_CONSTANTS.MODULE}.${WMS_PERMISSION_CONSTANTS.ACTIONS.MANAGE_GRN}`,
  MANAGE_GDO: `${WMS_PERMISSION_CONSTANTS.MODULE}.${WMS_PERMISSION_CONSTANTS.ACTIONS.MANAGE_GDO}`,
  MANAGE_STOCK: `${WMS_PERMISSION_CONSTANTS.MODULE}.${WMS_PERMISSION_CONSTANTS.ACTIONS.MANAGE_STOCK}`,
  MANAGE_TRANSFERS: `${WMS_PERMISSION_CONSTANTS.MODULE}.${WMS_PERMISSION_CONSTANTS.ACTIONS.MANAGE_TRANSFERS}`,
  MANAGE_STORAGE: `${WMS_PERMISSION_CONSTANTS.MODULE}.${WMS_PERMISSION_CONSTANTS.ACTIONS.MANAGE_STORAGE}`,
  MANAGE_SETTINGS: `${WMS_PERMISSION_CONSTANTS.MODULE}.${WMS_PERMISSION_CONSTANTS.ACTIONS.MANAGE_SETTINGS}`,
  VIEW_REPORTS: `${WMS_PERMISSION_CONSTANTS.MODULE}.${WMS_PERMISSION_CONSTANTS.ACTIONS.VIEW_REPORTS}`,
} as const;
