export const HR_PERMISSION_CONSTANTS = {
  MODULE: 'hr',
  ACTIONS: {
    VIEW: 'view',
    MANAGE_EMPLOYEES: 'manage_employees',
    MANAGE_LEAVE: 'manage_leave',
    APPROVE_LEAVE: 'approve_leave',
    MANAGE_PAYROLL: 'manage_payroll',
    MANAGE_LOANS: 'manage_loans',
    MANAGE_TIMESHEETS: 'manage_timesheets',
    MANAGE_EVALUATIONS: 'manage_evaluations',
    GENERATE_LETTERS: 'generate_letters',
    VIEW_SELF: 'view_self',
  },
} as const;

export const HR_PERMISSIONS = {
  VIEW: `${HR_PERMISSION_CONSTANTS.MODULE}.${HR_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  MANAGE_EMPLOYEES: `${HR_PERMISSION_CONSTANTS.MODULE}.${HR_PERMISSION_CONSTANTS.ACTIONS.MANAGE_EMPLOYEES}`,
  MANAGE_LEAVE: `${HR_PERMISSION_CONSTANTS.MODULE}.${HR_PERMISSION_CONSTANTS.ACTIONS.MANAGE_LEAVE}`,
  APPROVE_LEAVE: `${HR_PERMISSION_CONSTANTS.MODULE}.${HR_PERMISSION_CONSTANTS.ACTIONS.APPROVE_LEAVE}`,
  MANAGE_PAYROLL: `${HR_PERMISSION_CONSTANTS.MODULE}.${HR_PERMISSION_CONSTANTS.ACTIONS.MANAGE_PAYROLL}`,
  MANAGE_LOANS: `${HR_PERMISSION_CONSTANTS.MODULE}.${HR_PERMISSION_CONSTANTS.ACTIONS.MANAGE_LOANS}`,
  MANAGE_TIMESHEETS: `${HR_PERMISSION_CONSTANTS.MODULE}.${HR_PERMISSION_CONSTANTS.ACTIONS.MANAGE_TIMESHEETS}`,
  MANAGE_EVALUATIONS: `${HR_PERMISSION_CONSTANTS.MODULE}.${HR_PERMISSION_CONSTANTS.ACTIONS.MANAGE_EVALUATIONS}`,
  GENERATE_LETTERS: `${HR_PERMISSION_CONSTANTS.MODULE}.${HR_PERMISSION_CONSTANTS.ACTIONS.GENERATE_LETTERS}`,
  VIEW_SELF: `${HR_PERMISSION_CONSTANTS.MODULE}.${HR_PERMISSION_CONSTANTS.ACTIONS.VIEW_SELF}`,
} as const;
