export const PARTIES_PERMISSION_CONSTANTS = {
  MODULE: "parties",
  ACTIONS: {
    VIEW: "view",
    CREATE: "create",
    UPDATE: "update",
    DELETE: "delete",
    MANAGE_CREDIT: "manage_credit",
  },
} as const;

export const PARTIES_PERMISSIONS = {
  VIEW: `${PARTIES_PERMISSION_CONSTANTS.MODULE}.${PARTIES_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  CREATE: `${PARTIES_PERMISSION_CONSTANTS.MODULE}.${PARTIES_PERMISSION_CONSTANTS.ACTIONS.CREATE}`,
  UPDATE: `${PARTIES_PERMISSION_CONSTANTS.MODULE}.${PARTIES_PERMISSION_CONSTANTS.ACTIONS.UPDATE}`,
  DELETE: `${PARTIES_PERMISSION_CONSTANTS.MODULE}.${PARTIES_PERMISSION_CONSTANTS.ACTIONS.DELETE}`,
  MANAGE_CREDIT: `${PARTIES_PERMISSION_CONSTANTS.MODULE}.${PARTIES_PERMISSION_CONSTANTS.ACTIONS.MANAGE_CREDIT}`,
} as const;
