export const AWB_STOCK_PERMISSION_CONSTANTS = {
  MODULE: "awb_stock",
  ACTIONS: {
    VIEW: "view",
    CREATE: "create",
    UPDATE: "update",
    DELETE: "delete",
    ALLOCATE: "allocate",
    VOID: "void",
  },
} as const;

export const AWB_STOCK_PERMISSIONS = {
  VIEW: `${AWB_STOCK_PERMISSION_CONSTANTS.MODULE}.${AWB_STOCK_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  CREATE: `${AWB_STOCK_PERMISSION_CONSTANTS.MODULE}.${AWB_STOCK_PERMISSION_CONSTANTS.ACTIONS.CREATE}`,
  UPDATE: `${AWB_STOCK_PERMISSION_CONSTANTS.MODULE}.${AWB_STOCK_PERMISSION_CONSTANTS.ACTIONS.UPDATE}`,
  DELETE: `${AWB_STOCK_PERMISSION_CONSTANTS.MODULE}.${AWB_STOCK_PERMISSION_CONSTANTS.ACTIONS.DELETE}`,
  ALLOCATE: `${AWB_STOCK_PERMISSION_CONSTANTS.MODULE}.${AWB_STOCK_PERMISSION_CONSTANTS.ACTIONS.ALLOCATE}`,
  VOID: `${AWB_STOCK_PERMISSION_CONSTANTS.MODULE}.${AWB_STOCK_PERMISSION_CONSTANTS.ACTIONS.VOID}`,
} as const;
