export const REPORTS_PERMISSION_CONSTANTS = {
  MODULE: "reports",
  ACTIONS: {
    READ: "read",
    GENERATE: "generate",
  },
} as const;

export const REPORTS_PERMISSIONS = {
  READ: `${REPORTS_PERMISSION_CONSTANTS.MODULE}.${REPORTS_PERMISSION_CONSTANTS.ACTIONS.READ}`,
  GENERATE: `${REPORTS_PERMISSION_CONSTANTS.MODULE}.${REPORTS_PERMISSION_CONSTANTS.ACTIONS.GENERATE}`,
} as const;
