export const CRM_PERMISSION_CONSTANTS = {
  MODULE: 'crm',
  ACTIONS: {
    VIEW: 'view',
    CREATE: 'create',
    UPDATE: 'update',
    DELETE: 'delete',
  },
} as const;

export const CRM_PERMISSIONS = {
  VIEW: `${CRM_PERMISSION_CONSTANTS.MODULE}.${CRM_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  CREATE: `${CRM_PERMISSION_CONSTANTS.MODULE}.${CRM_PERMISSION_CONSTANTS.ACTIONS.CREATE}`,
  UPDATE: `${CRM_PERMISSION_CONSTANTS.MODULE}.${CRM_PERMISSION_CONSTANTS.ACTIONS.UPDATE}`,
  DELETE: `${CRM_PERMISSION_CONSTANTS.MODULE}.${CRM_PERMISSION_CONSTANTS.ACTIONS.DELETE}`,
} as const;
