export const PORTAL_PERMISSION_CONSTANTS = {
  MODULE: 'portal',
  ACTIONS: {
    MANAGE_USERS: 'manage_users',
    VIEW_USERS: 'view_users',
    VIEW_PERMISSIONS: 'view_permissions',
    MANAGE_PERMISSIONS: 'manage_permissions',
  },
} as const;

export const PORTAL_PERMISSIONS = {
  MANAGE_USERS: `${PORTAL_PERMISSION_CONSTANTS.MODULE}.${PORTAL_PERMISSION_CONSTANTS.ACTIONS.MANAGE_USERS}`,
  VIEW_USERS: `${PORTAL_PERMISSION_CONSTANTS.MODULE}.${PORTAL_PERMISSION_CONSTANTS.ACTIONS.VIEW_USERS}`,
  VIEW_PERMISSIONS: `${PORTAL_PERMISSION_CONSTANTS.MODULE}.${PORTAL_PERMISSION_CONSTANTS.ACTIONS.VIEW_PERMISSIONS}`,
  MANAGE_PERMISSIONS: `${PORTAL_PERMISSION_CONSTANTS.MODULE}.${PORTAL_PERMISSION_CONSTANTS.ACTIONS.MANAGE_PERMISSIONS}`,
} as const;

/** Default document rights when staff has not configured a matrix yet. */
export const DEFAULT_PORTAL_DOCUMENT_TYPES = [
  'HAWB',
  'MAWB',
  'HBL',
  'MBL',
  'INVOICE',
  'CREDIT_NOTE',
  'STATEMENT',
  'CAN',
  'DO',
  'POD',
  'PRE_ALERT',
  'OTHER',
] as const;
