export const PORTAL_PERMISSION_CONSTANTS = {
  MODULE: 'portal',
  ACTIONS: {
    MANAGE_USERS: 'manage_users',
    VIEW_USERS: 'view_users',
  },
} as const;

export const PORTAL_PERMISSIONS = {
  MANAGE_USERS: `${PORTAL_PERMISSION_CONSTANTS.MODULE}.${PORTAL_PERMISSION_CONSTANTS.ACTIONS.MANAGE_USERS}`,
  VIEW_USERS: `${PORTAL_PERMISSION_CONSTANTS.MODULE}.${PORTAL_PERMISSION_CONSTANTS.ACTIONS.VIEW_USERS}`,
} as const;
