export const NVOCC_PERMISSION_CONSTANTS = {
  MODULE: "nvocc",
  ACTIONS: {
    VIEW: "view",
    MANAGE: "manage",
  },
} as const;

export const NVOCC_PERMISSIONS = {
  VIEW: `${NVOCC_PERMISSION_CONSTANTS.MODULE}.${NVOCC_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  MANAGE: `${NVOCC_PERMISSION_CONSTANTS.MODULE}.${NVOCC_PERMISSION_CONSTANTS.ACTIONS.MANAGE}`,
} as const;
