/** NVOCC job milestones (Week 20 plan — 22 steps). */
export const NVOCC_MILESTONES = [
  'ENQUIRY_RECEIVED',
  'BOOKING_CONFIRMED',
  'SI_SUBMITTED',
  'VGM_SUBMITTED',
  'CY_CUTOFF_PASSED',
  'CARGO_RECEIVED_AT_CFS',
  'CARGO_STUFFED',
  'VESSEL_LOADED',
  'VESSEL_SAILED',
  'HBL_ISSUED',
  'MBL_RECEIVED',
  'PRE_ALERT_SENT',
  'CARGO_IN_TRANSIT',
  'CARGO_ARRIVED_POD',
  'CAN_SENT',
  'CUSTOMS_CLEARED',
  'DO_ISSUED',
  'CARGO_DELIVERED',
  'POD_RECEIVED',
  'INVOICE_RAISED',
  'PAYMENT_RECEIVED',
  'JOB_CLOSED',
] as const;

export const NVOCC_CREATE_MILESTONE = 'BOOKING_CONFIRMED';
