-- Email share event types for staff/vendor document emailing
ALTER TYPE "EmailEventType" ADD VALUE IF NOT EXISTS 'AR_STATEMENT';
ALTER TYPE "EmailEventType" ADD VALUE IF NOT EXISTS 'AP_STATEMENT';
ALTER TYPE "EmailEventType" ADD VALUE IF NOT EXISTS 'REMITTANCE_SEND';
ALTER TYPE "EmailEventType" ADD VALUE IF NOT EXISTS 'CREDIT_SUMMARY_SEND';
ALTER TYPE "EmailEventType" ADD VALUE IF NOT EXISTS 'VENDOR_SHARE_PROOF';
ALTER TYPE "EmailEventType" ADD VALUE IF NOT EXISTS 'VENDOR_SHARE_INVOICE';
ALTER TYPE "EmailEventType" ADD VALUE IF NOT EXISTS 'VENDOR_SHARE_DISPUTE';
