export const GL_PERMISSION_CONSTANTS = {
  MODULE: 'gl',
  ACTIONS: {
    VIEW: 'view',
    CREATE: 'create',
    UPDATE: 'update',
    DELETE: 'delete',
    POST: 'post',
    REVERSE: 'reverse',
    MANAGE_COA: 'manage_coa',
  },
} as const;

export const GL_PERMISSIONS = {
  VIEW: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  CREATE: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.CREATE}`,
  UPDATE: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.UPDATE}`,
  DELETE: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.DELETE}`,
  POST: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.POST}`,
  REVERSE: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.REVERSE}`,
  MANAGE_COA: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.MANAGE_COA}`,
} as const;
