export const GL_PERMISSION_CONSTANTS = {
  MODULE: 'gl',
  ACTIONS: {
    VIEW: 'view',
    CREATE: 'create',
    UPDATE: 'update',
    DELETE: 'delete',
    POST: 'post',
    REVERSE: 'reverse',
    MANAGE_COA: 'manage_coa',
    MANAGE_PAYMENTS: 'manage_payments',
    MANAGE_CHEQUES: 'manage_cheques',
    RECONCILE: 'reconcile',
    VIEW_AGING: 'view_aging',
    VIEW_REPORTS: 'view_reports',
    MANAGE_REPORTS: 'manage_reports',
  },
} as const;

export const GL_PERMISSIONS = {
  VIEW: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  CREATE: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.CREATE}`,
  UPDATE: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.UPDATE}`,
  DELETE: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.DELETE}`,
  POST: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.POST}`,
  REVERSE: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.REVERSE}`,
  MANAGE_COA: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.MANAGE_COA}`,
  MANAGE_PAYMENTS: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.MANAGE_PAYMENTS}`,
  MANAGE_CHEQUES: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.MANAGE_CHEQUES}`,
  RECONCILE: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.RECONCILE}`,
  VIEW_AGING: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.VIEW_AGING}`,
  VIEW_REPORTS: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.VIEW_REPORTS}`,
  MANAGE_REPORTS: `${GL_PERMISSION_CONSTANTS.MODULE}.${GL_PERMISSION_CONSTANTS.ACTIONS.MANAGE_REPORTS}`,
} as const;
