-- Week 8 — Sea FCL Export document generation (Ch.10 / Ch.16)

ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'HBL_EXPRESS_RELEASE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'FIATA_BL';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'RIDER_BL';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SWITCH_BL';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PROXY_BL';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'BACK_TO_BACK_BL';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SURRENDER_NOTICE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'STUFFING_REPORT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SAILING_CONFIRMATION';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'TRANSHIPMENT_CONFIRMATION';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'JOB_PNL';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PROFORMA_INVOICE';

ALTER TABLE "sea_fcl_job_details"
  ADD COLUMN IF NOT EXISTS "transhipment_port" VARCHAR(200),
  ADD COLUMN IF NOT EXISTS "sailed_at" TIMESTAMPTZ;

ALTER TABLE "bills_of_lading"
  ADD COLUMN IF NOT EXISTS "vessel_name" VARCHAR(200),
  ADD COLUMN IF NOT EXISTS "voyage_number" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "etd" TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "eta" TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "freight_terms" VARCHAR(30),
  ADD COLUMN IF NOT EXISTS "bl_conditions" TEXT,
  ADD COLUMN IF NOT EXISTS "rider_terms" TEXT,
  ADD COLUMN IF NOT EXISTS "switched_from_bl_number" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "switch_consignee_id" UUID,
  ADD COLUMN IF NOT EXISTS "switch_notify_id" UUID,
  ADD COLUMN IF NOT EXISTS "proxy_forwarder_name" VARCHAR(200),
  ADD COLUMN IF NOT EXISTS "proxy_forwarder_address" TEXT,
  ADD COLUMN IF NOT EXISTS "paired_bl_id" UUID,
  ADD COLUMN IF NOT EXISTS "finalized_at" TIMESTAMPTZ;

ALTER TABLE "document_generation_tasks"
  ADD COLUMN IF NOT EXISTS "options" JSONB;
