import { Controller, Get, NotFoundException, Param, Res, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiOperation, ApiTags } from '@nestjs/swagger';
import { Response } from 'express';
import * as fs from 'fs/promises';
import { StorageService } from '../shared/storage/storage.service';
import { RolesGuard } from '../modules/users/guards/roles.guard';
import { CurrentUser } from '../modules/users/decorators/current-user.decorator';

@ApiTags('Files')
@ApiBearerAuth()
@UseGuards(RolesGuard)
@Controller('files')
export class FilesController {
  constructor(private readonly storage: StorageService) {}

  @Get(':tenantId/:filename')
  @ApiOperation({ summary: 'Download a locally stored file (PDFs generated by the system)' })
  async download(
    @CurrentUser('tenantId') userTenantId: string,
    @Param('tenantId') tenantId: string,
    @Param('filename') filename: string,
    @Res() res: Response,
  ) {
    if (userTenantId !== tenantId) {
      throw new NotFoundException('File not found.');
    }

    const filePath = this.storage.resolveLocalPath(tenantId, decodeURIComponent(filename));

    try {
      const buffer = await fs.readFile(filePath);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `inline; filename="${filename}"`);
      res.send(buffer);
    } catch {
      throw new NotFoundException('File not found.');
    }
  }
}
