import {
  BadRequestException,
  Controller,
  Get,
  NotFoundException,
  Param,
  Res,
  UseGuards,
} from '@nestjs/common';
import { ApiBearerAuth, ApiOperation, ApiTags } from '@nestjs/swagger';
import { Response } from 'express';
import * as fs from 'fs/promises';
import { StorageService } from '../shared/storage/storage.service';
import { RolesGuard } from '../modules/users/guards/roles.guard';
import { CurrentUser } from '../modules/users/decorators/current-user.decorator';
import { isSuperAdminPrincipal } from '../common/utils/principal.util';

@ApiTags('Files')
@ApiBearerAuth()
@UseGuards(RolesGuard)
@Controller('files')
export class FilesController {
  constructor(private readonly storage: StorageService) {}

  @Get(':tenantId/:filename')
  @ApiOperation({
    summary: 'Download a locally stored file (PDFs generated by the system)',
    description: 'Caller tenant must match URL tenantId (SuperAdmin excluded from this route by design).',
  })
  async download(
    @CurrentUser() principal: unknown,
    @CurrentUser('tenantId') userTenantId: string | undefined,
    @Param('tenantId') tenantId: string,
    @Param('filename') filename: string,
    @Res() res: Response,
  ) {
    // SuperAdmin has no tenant — refuse rather than allow cross-tenant reads via this path.
    if (isSuperAdminPrincipal(principal) || !userTenantId) {
      throw new NotFoundException('File not found.');
    }

    if (userTenantId !== tenantId) {
      throw new NotFoundException('File not found.');
    }

    let filePath: string;
    try {
      filePath = this.storage.resolveLocalPath(tenantId, decodeURIComponent(filename));
    } catch {
      throw new BadRequestException('Invalid filename.');
    }

    try {
      const buffer = await fs.readFile(filePath);
      const safeDownloadName = filePath.split(/[/\\]/).pop() ?? 'file.pdf';
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `inline; filename="${safeDownloadName}"`);
      res.send(buffer);
    } catch {
      throw new NotFoundException('File not found.');
    }
  }
}
