export const INVOICES_PERMISSION_CONSTANTS = {
  MODULE: "invoices",
  ACTIONS: {
    VIEW: "view",
    CREATE: "create",
    UPDATE: "update",
    DELETE: "delete",
    POST: "post",
    SEND: "send",
    APPROVE_PAYMENT: "approve_payment",
  },
} as const;

export const INVOICES_PERMISSIONS = {
  VIEW: `${INVOICES_PERMISSION_CONSTANTS.MODULE}.${INVOICES_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  CREATE: `${INVOICES_PERMISSION_CONSTANTS.MODULE}.${INVOICES_PERMISSION_CONSTANTS.ACTIONS.CREATE}`,
  UPDATE: `${INVOICES_PERMISSION_CONSTANTS.MODULE}.${INVOICES_PERMISSION_CONSTANTS.ACTIONS.UPDATE}`,
  DELETE: `${INVOICES_PERMISSION_CONSTANTS.MODULE}.${INVOICES_PERMISSION_CONSTANTS.ACTIONS.DELETE}`,
  POST: `${INVOICES_PERMISSION_CONSTANTS.MODULE}.${INVOICES_PERMISSION_CONSTANTS.ACTIONS.POST}`,
  SEND: `${INVOICES_PERMISSION_CONSTANTS.MODULE}.${INVOICES_PERMISSION_CONSTANTS.ACTIONS.SEND}`,
  APPROVE_PAYMENT: `${INVOICES_PERMISSION_CONSTANTS.MODULE}.${INVOICES_PERMISSION_CONSTANTS.ACTIONS.APPROVE_PAYMENT}`,
} as const;
