export const QUOTE_REQUESTS_PERMISSION_CONSTANTS = {
  MODULE: "quote_requests",
  ACTIONS: {
    VIEW: "view",
    MANAGE_CONNECTION: "manage_connection",
    SYNC: "sync",
    UPDATE_STATUS: "update_status",
  },
} as const;

export const QUOTE_REQUESTS_PERMISSIONS = {
  VIEW: `${QUOTE_REQUESTS_PERMISSION_CONSTANTS.MODULE}.${QUOTE_REQUESTS_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  MANAGE_CONNECTION: `${QUOTE_REQUESTS_PERMISSION_CONSTANTS.MODULE}.${QUOTE_REQUESTS_PERMISSION_CONSTANTS.ACTIONS.MANAGE_CONNECTION}`,
  SYNC: `${QUOTE_REQUESTS_PERMISSION_CONSTANTS.MODULE}.${QUOTE_REQUESTS_PERMISSION_CONSTANTS.ACTIONS.SYNC}`,
  UPDATE_STATUS: `${QUOTE_REQUESTS_PERMISSION_CONSTANTS.MODULE}.${QUOTE_REQUESTS_PERMISSION_CONSTANTS.ACTIONS.UPDATE_STATUS}`,
} as const;
