export const QUOTATIONS_PERMISSION_CONSTANTS = {
  MODULE: "quotations",
  ACTIONS: {
    VIEW: "view",
    CREATE: "create",
    UPDATE: "update",
    DELETE: "delete",
    SUBMIT: "submit",
    APPROVE: "approve",
    SEND: "send",
    CLOSE: "close",
  },
} as const;

export const QUOTATIONS_PERMISSIONS = {
  VIEW: `${QUOTATIONS_PERMISSION_CONSTANTS.MODULE}.${QUOTATIONS_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
  CREATE: `${QUOTATIONS_PERMISSION_CONSTANTS.MODULE}.${QUOTATIONS_PERMISSION_CONSTANTS.ACTIONS.CREATE}`,
  UPDATE: `${QUOTATIONS_PERMISSION_CONSTANTS.MODULE}.${QUOTATIONS_PERMISSION_CONSTANTS.ACTIONS.UPDATE}`,
  DELETE: `${QUOTATIONS_PERMISSION_CONSTANTS.MODULE}.${QUOTATIONS_PERMISSION_CONSTANTS.ACTIONS.DELETE}`,
  SUBMIT: `${QUOTATIONS_PERMISSION_CONSTANTS.MODULE}.${QUOTATIONS_PERMISSION_CONSTANTS.ACTIONS.SUBMIT}`,
  APPROVE: `${QUOTATIONS_PERMISSION_CONSTANTS.MODULE}.${QUOTATIONS_PERMISSION_CONSTANTS.ACTIONS.APPROVE}`,
  SEND: `${QUOTATIONS_PERMISSION_CONSTANTS.MODULE}.${QUOTATIONS_PERMISSION_CONSTANTS.ACTIONS.SEND}`,
  CLOSE: `${QUOTATIONS_PERMISSION_CONSTANTS.MODULE}.${QUOTATIONS_PERMISSION_CONSTANTS.ACTIONS.CLOSE}`,
} as const;
