export const NOTIFICATIONS_PERMISSION_CONSTANTS = {
  MODULE: 'notifications',
  ACTIONS: {
    VIEW: 'view',
  },
} as const;

export const NOTIFICATIONS_PERMISSIONS = {
  VIEW: `${NOTIFICATIONS_PERMISSION_CONSTANTS.MODULE}.${NOTIFICATIONS_PERMISSION_CONSTANTS.ACTIONS.VIEW}`,
} as const;
